### ISSUE TITLE
[FEAT]: Heroku with GitHub Actions

### ISSUE THREAD

**Issue by ervinteoh** [ervinteoh/flask-login#21]
### Issue Overview

**Description**
A short excerpt describing the cause and effect of the issue.

### Tasks
- [x] Webpack Separate CSS
- [x] Refactor
- [x] Production Gmail
- [ ] Cleanup Pipeline
- [ ] Heroku Project Setup
- [ ] GitHub Actions Deployment
